server:
  host: ":8081"
  timeout: 10s
database:
  port: "5432"
  user: "postgres"
  password: "alex1234"
  dbname: "postgres"
  host: "postgres"
redis:
  redis_address: "redis:6379"
  redis_password: ""
  redis_db: 0
