server:
  host: ":8080"
  timeout: 10s
database:
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "crypto"
  host: "db" 
redis:
  redis_address: "redis:6379"
  redis_password: ""
  redis_db: 0